# Generated by Django 3.1.6 on 2021-02-12 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210212_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount_to_order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
