# Generated by Django 3.1.6 on 2021-02-14 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 14, 4, 20, 29, 924280)),
        ),
    ]
