# Generated by Django 3.1.6 on 2021-02-18 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 5, 27, 41, 445922)),
        ),
    ]
