# Generated by Django 3.1.6 on 2021-02-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210213_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
