# Generated by Django 3.1.6 on 2021-02-28 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210218_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 28, 14, 25, 43, 576340)),
        ),
    ]
