# Generated by Django 3.1.6 on 2021-02-17 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210217_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 3, 20, 13, 768416)),
        ),
    ]
