# Generated by Django 3.1.6 on 2021-02-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orders_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipped',
        ),
    ]
