# Generated by Django 3.1.6 on 2021-03-03 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210228_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 23, 37, 19, 3843)),
        ),
    ]
