# Generated by Django 3.1.6 on 2021-03-02 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210302_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 16, 57, 34, 363061)),
        ),
    ]
